### ISSUE TITLE
Node not found in packages\Npm.js.2.13.1.0?

### ISSUE THREAD

**Issue by fredbutters** [giggio/npm-nuget#12]
I'm using VS2015. I have the Node 4.0.0.0 and NPM 2.13.1 NuGet packages installed but keep getting this error when building. I'm not even sure what it means. We noticed it first when another developer running VS2013 tried to open my solution, in case the different versions of VS has something to do with this.

Any ideas? Thanks

VS 11 Common Tools not found
VS 12 Common Tools not found
'"C:\WebDev\TEST\packages\Npm.js.2.13.1.0\tools\..\..\Node.js.4.0.0\node.exe"' is not recognized as an internal or external command,
operable program or batch file.

The command "
IF EXIST "%VS110COMNTOOLS%VsDevCmd.bat" (
call "%VS110COMNTOOLS%VsDevCmd.bat"
) ELSE (
echo VS 11 Common Tools not found
)
IF EXIST "%VS120COMNTOOLS%VsDevCmd.bat" (
call "%VS120COMNTOOLS%VsDevCmd.bat"
) ELSE (
echo VS 12 Common Tools not found
)
set PATH=C:\WebDev\TEST\packages\Npm.js.2.13.1.0\build\..\tools\;%PATH%
"C:\WebDev\TEST\packages\Npm.js.2.13.1.0\build\..\tools\npm" install
" exited with code 1.

**Comment by giggio** [comment]
Don't use this package with VS 2015. There is native support for NPM on VS 2015.
