### ISSUE TITLE
Please bump to NPM 3

### ISSUE THREAD

**Issue by ffMathy** [giggio/npm-nuget#13]
NPM 3 allows directory flattening, and support in Visual Studio 2015 Update 1 is horrible (the inbuilt support doesn't always flatten directories). Can we bump to NPM 3?

I don't think we'll ever need a later version.

**Comment by giggio** [comment]
You can use NPM 3 with VS, you simply need to change your options.
Go to Tools > Options > Projects and Solutions > External Web Tools
Change the directory order.
I am not planning on updating this package anymore, now that we have 2015. It is redundant and unnecessary now. It is what it is.

**Comment by ffMathy** [comment]
I am well aware that it is possible to change the directory order. We just don't want to ask 14 developers to do that every time they set up their development environment. I work for a major corporation where stuff like this matters.

What if I made a pull request to upgrade?

**Comment by giggio** [comment]
If you work for a large corporation it is even easier. It is a registry thing, just push it through the corporate domain to everyone into a certain profile and you are done. This is something I already did with some clients.

But if you send a PR I can integrate it. This is still much more inferior than what we got in the box at the moment, I **do not** recommend it.

**Comment by ffMathy** [comment]
I will do my best and submit a pull request today.

**Comment by ffMathy** [comment]
I have created #14 now. Please review and merge if it looks good.

**Comment by ffMathy** [comment]
Also, in regards to your latest comment. It is *not* easy to get that kind of stuff done in a larger corporation. I don't think they would allow pollution in their scripts or domain policies like that.

**Comment by ffMathy** [comment]
Oh, and merry christmas. I appreciate that you are willing to look into this.
